### ISSUE TITLE
How to run the tests locally?

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari-animation#168]
I'm having trouble testing this package locally.
* With pytest, it complains that qtbot is not available for the `make_napari_viewer` fixture. I tried installing qtbot and giving things another go, but that didn't help.
* With tox
    * tox on Windows - it finds the one matching tox configuration that matches the local environment, but hangs for a really long time when installing the dependencies. I've left it going, but I don't think it's going to actually run. *EDIT: I left it overnight and it did finally run, hooray! Nevertheless, I usually work on a Mac, so this might not help me that much.*
    * tox on Mac - all tox configurations are skipped, and I get these errors
```
py310-macos-pyqt: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'DISPLAY XAUTHORITY'
py310-macos-pyqt: FAIL ✖ in 0 seconds
py310-macos-pyside: failed with pass_env values cannot contain whitespace, use comma to have multiple values in a single line, invalid values found 'DISPLAY XAUTHORITY'
```

The README says *"...a detailed contributing guide is coming soon."*, so perhaps whatever the answer to this problem is could become part of the not-yet-existing developer contributing guide?

**Comment by alisterburt** [comment]
ooh - sorry about this

I'm also on a mac and running tests with pytest
```
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
PyQt5 5.15.7 -- Qt runtime 5.15.4 -- Qt compiled 5.15.4
rootdir: /Users/alisterburt/programming/napari-animation, configfile: setup.cfg
plugins: qt-4.1.0, napari-0.4.16, napari-plugin-engine-0.2.0, npe2-0.6.1
collected 97 items                            
```

What is the error you're getting? How are you installing `pytest-qt`?

**Comment by alisterburt** [comment]
agree that this would be great in a contributing guide and sorry for the false advertising in the readme - is leftover from when we were pushing hard on this and had grand plans 😆

**Comment by GenevieveBuckley** [comment]
> I'm also on a mac and running tests with pytest

Can I see your (working) conda list? That might be helpful

**Comment by GenevieveBuckley** [comment]
First I tried this...
```
conda create -n napari-animation-dev python=3.10 pip ipython
conda activate napari-animation-dev
python -m pip install -e ".[dev]"
```

But that gave me an error installing pyqt.
<details>
<summary>Details (click to expand)</summary>

```
Obtaining file:///Users/genevieb/Documents/GitHub/temp/napari-animation
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting imageio (from napari-animation==0.0.6.dev6+gf506832)
  Downloading imageio-2.28.0-py3-none-any.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 25.9 MB/s eta 0:00:00
Collecting imageio-ffmpeg (from napari-animation==0.0.6.dev6+gf506832)
  Using cached imageio_ffmpeg-0.4.8-py3-none-any.whl
Collecting napari (from napari-animation==0.0.6.dev6+gf506832)
  Using cached napari-0.4.17-py3-none-any.whl (2.6 MB)
Collecting npe2 (from napari-animation==0.0.6.dev6+gf506832)
  Downloading npe2-0.7.0-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 3.5 MB/s eta 0:00:00
Collecting numpy (from napari-animation==0.0.6.dev6+gf506832)
  Downloading numpy-1.24.3-cp310-cp310-macosx_11_0_arm64.whl (13.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 20.3 MB/s eta 0:00:00
Collecting qtpy (from napari-animation==0.0.6.dev6+gf506832)
  Using cached QtPy-2.3.1-py3-none-any.whl (84 kB)
Collecting scipy (from napari-animation==0.0.6.dev6+gf506832)
  Using cached scipy-1.10.1-cp310-cp310-macosx_12_0_arm64.whl (28.8 MB)
Collecting tqdm>=4.56.0 (from napari-animation==0.0.6.dev6+gf506832)
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting superqt (from napari-animation==0.0.6.dev6+gf506832)
  Using cached superqt-0.4.1-py3-none-any.whl (63 kB)
Collecting pre-commit (from napari-animation==0.0.6.dev6+gf506832)
  Using cached pre_commit-3.2.2-py2.py3-none-any.whl (202 kB)
Collecting black (from napari-animation==0.0.6.dev6+gf506832)
  Using cached black-23.3.0-cp310-cp310-macosx_10_16_universal2.whl (2.7 MB)
Collecting flake8 (from napari-animation==0.0.6.dev6+gf506832)
  Using cached flake8-6.0.0-py2.py3-none-any.whl (57 kB)
Collecting check-manifest (from napari-animation==0.0.6.dev6+gf506832)
  Using cached check_manifest-0.49-py3-none-any.whl (20 kB)
Collecting PyQt5!=5.15.0,>=5.12.3 (from napari-animation==0.0.6.dev6+gf506832)
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/Users/genevieb/mambaforge/envs/napari-animation-dev/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/genevieb/mambaforge/envs/napari-animation-dev/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/genevieb/mambaforge/envs/napari-animation-dev/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/82/phlx_f6j5518qtvpm4x0_0fm0000gq/T/pip-build-env-idhua02i/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/82/phlx_f6j5518qtvpm4x0_0fm0000gq/T/pip-build-env-idhua02i/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/82/phlx_f6j5518qtvpm4x0_0fm0000gq/T/pip-build-env-idhua02i/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 602, in setup
          self.update(tool)
        File "/private/var/folders/82/phlx_f6j5518qtvpm4x0_0fm0000gq/T/pip-install-8svxhrwd/pyqt5_b3f6009047a945be82e1d1569810fdd5/project.py", line 165, in update
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
</details>

I didn't think that was too unusual, I often find pyqt is difficult to install on an M1 mac. It works well now if you install with conda, but you used to need a special conda channel, and I still find problems with pip. So that's ok, I figured I'd just go through the dependency list and install them one by one.

**Comment by GenevieveBuckley** [comment]
Figured it out!
I needed to install `pytest-qt`, which wasn't on the requirements list. I was too focused on trying to install `qtbot` in different ways to think about that.

**Comment by GenevieveBuckley** [comment]
This worked! (needed to add pytest-qt and qtbot, which weren't listed in the setup.cfg)
```
conda create -n napari-animation-dev python=3.10 pip ipython
conda activate napari-animation-dev
# Install requirements
mamba install napari npe2 qtpy superqt
mamba install imageio imageio-ffmpeg
mamba install scipy tqdm
# Install development dependencies
mamba install pre-commit black flake8 check-manifest
mamba install pytest pytest-qt
python -m pip install qtbot
# Install development version
cd napari-animation
python -m pip install -e .
# Run pytest
pytest
```

**Comment by GenevieveBuckley** [comment]
@alisterburt how do you feel about shifting the PyQt requirement into its own optional dependency category?

Why is this line listed so specifically https://github.com/napari/napari-animation/blob/f5068324521be61bda6e89c333161d0e660cd4fc/setup.cfg#L51

Then you could have the contributing docs go something like this, and work for all operating systems:
```
conda create napari-animation-dev python=3.10 pip ipython
conda activate napari-animation-dev
git clone https://github.com/napari/napari-animation.git
cd napari-animation
python -m pip install -e .[dev]
```
So users can possibly have an optional choice of how and where to install pyqt/pyside (is pyside supported by napari-animation?)
```
python -m pip install -e .[pyqt]
# or
conda install pyqt
# etc.
```

**Comment by psobolewskiPhD** [comment]
So obviously contributing documentation is inadequate, but we still have some options to improve things:
1. just document that you need to install `.[testing, dev]`
2. have [dev] install [testing] -- this is how it works in the napari/napari repo

Anyone have any thoughts?
