### ISSUE TITLE
when clicking save nothing happens

### ISSUE THREAD

**Issue by joaomamede** [napari/napari-animation#36]
I have this error when trying to save.

```
Traceback (most recent call last):
  File "/home/jmamede/napari-animation/napari_animation/_qt/dialogs/save_dialog.py", line 49, in accept
    self.animate_function(save_path)
  File "/home/jmamede/napari-animation/napari_animation/animation.py", line 228, in animate
    writer = imageio.get_writer(
  File "/home/jmamede/.local/lib/python3.8/site-packages/imageio/core/functions.py", line 231, in get_writer
    return format.get_writer(request)
  File "/home/jmamede/.local/lib/python3.8/site-packages/imageio/core/format.py", line 185, in get_writer
    return self.Writer(self, request)
  File "/home/jmamede/.local/lib/python3.8/site-packages/imageio/core/format.py", line 221, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/jmamede/.local/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 354, in _open
    raise TypeError("Invalid arg for PNG writer: %r" % key)
TypeError: Invalid arg for PNG writer: 'fps'

If you suspect this is an IPython 7.21.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True


```

**Comment by alisterburt** [comment]
Thanks for reporting! This can be solved by installing the imageio-ffmpeg package until a fix is available

**Comment by sofroniewn** [comment]
> This can be solved by installing the imageio-ffmpeg package until a fix is available

This has now been added by default in #35, so I think we can now close. If this still doesn't work though please feel free to reopen

**Comment by joaomamede** [comment]
It works perfectly with the git clone I just did. 
Thanks so much for getting this, it's just what I need!
